name: Build Succeeds on PR

on:
  pull_request:
    branches:
      main

jobs:
  build:
    name: Build the project
    runs-on: ubuntu-latest
    environment: Monorepo
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Set Environment Variables
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV

      - name: Generate Prisma Client
        run: npm run db:generate

      - name: Install Dependencies
        run: npm install

      - name: Run Build
        run: npm run build